UPDATE `mine location` SET `Region Mine`='Alabama' WHERE `Region Mine`='AL';
UPDATE `mine location` SET `Region Mine`='Alaska' WHERE `Region Mine`='AK';
UPDATE `mine location` SET `Region Mine`='Arizona' WHERE `Region Mine`='AZ';
UPDATE `mine location` SET `Region Mine`='Arkansas' WHERE `Region Mine`='AR';
UPDATE `mine location` SET `Region Mine`='California' WHERE `Region Mine`='CA';
UPDATE `mine location` SET `Region Mine`='Colorado' WHERE `Region Mine`='CO';
UPDATE `mine location` SET `Region Mine`='Connecticut' WHERE `Region Mine`='CT';
UPDATE `mine location` SET `Region Mine`='Delaware' WHERE `Region Mine`='DE';
UPDATE `mine location` SET `Region Mine`='District of Columbia' WHERE `Region Mine`='DC';
UPDATE `mine location` SET `Region Mine`='Florida' WHERE `Region Mine`='FL';
UPDATE `mine location` SET `Region Mine`='Georgia' WHERE `Region Mine`='GA';
UPDATE `mine location` SET `Region Mine`='Hawaii' WHERE `Region Mine`='HI';
UPDATE `mine location` SET `Region Mine`='Idaho' WHERE `Region Mine`='ID';
UPDATE `mine location` SET `Region Mine`='Illinois' WHERE `Region Mine`='IL';
UPDATE `mine location` SET `Region Mine`='Indiana' WHERE `Region Mine`='IN';
UPDATE `mine location` SET `Region Mine`='Iowa' WHERE `Region Mine`='IA';
UPDATE `mine location` SET `Region Mine`='Kansas' WHERE `Region Mine`='KS';
UPDATE `mine location` SET `Region Mine`='Kentucky' WHERE `Region Mine`='KY';
UPDATE `mine location` SET `Region Mine`='Louisiana' WHERE `Region Mine`='LA';
UPDATE `mine location` SET `Region Mine`='Maine' WHERE `Region Mine`='ME';
UPDATE `mine location` SET `Region Mine`='Maryland' WHERE `Region Mine`='MD';
UPDATE `mine location` SET `Region Mine`='Massachusetts' WHERE `Region Mine`='MA';
UPDATE `mine location` SET `Region Mine`='Michigan' WHERE `Region Mine`='MI';
UPDATE `mine location` SET `Region Mine`='Minnesota' WHERE `Region Mine`='MN';
UPDATE `mine location` SET `Region Mine`='Mississippi' WHERE `Region Mine`='MS';
UPDATE `mine location` SET `Region Mine`='Missouri' WHERE `Region Mine`='MO';
UPDATE `mine location` SET `Region Mine`='Montana' WHERE `Region Mine`='MT';
UPDATE `mine location` SET `Region Mine`='Nebraska' WHERE `Region Mine`='NE';
UPDATE `mine location` SET `Region Mine`='Nevada' WHERE `Region Mine`='NV';
UPDATE `mine location` SET `Region Mine`='New Hampshire' WHERE `Region Mine`='NH';
UPDATE `mine location` SET `Region Mine`='New Jersey' WHERE `Region Mine`='NJ';
UPDATE `mine location` SET `Region Mine`='New Mexico' WHERE `Region Mine`='NM';
UPDATE `mine location` SET `Region Mine`='New York' WHERE `Region Mine`='NY';
UPDATE `mine location` SET `Region Mine`='North Carolina' WHERE `Region Mine`='NC';
UPDATE `mine location` SET `Region Mine`='North Dakota' WHERE `Region Mine`='ND';
UPDATE `mine location` SET `Region Mine`='Ohio' WHERE `Region Mine`='OH';
UPDATE `mine location` SET `Region Mine`='Oklahoma' WHERE `Region Mine`='OK';
UPDATE `mine location` SET `Region Mine`='Oregon' WHERE `Region Mine`='OR';
UPDATE `mine location` SET `Region Mine`='Pennsylvania' WHERE `Region Mine`='PA';
UPDATE `mine location` SET `Region Mine`='Rhode Island' WHERE `Region Mine`='RI';
UPDATE `mine location` SET `Region Mine`='South Carolina' WHERE `Region Mine`='SC';
UPDATE `mine location` SET `Region Mine`='South Dakota' WHERE `Region Mine`='SD';
UPDATE `mine location` SET `Region Mine`='Tennessee' WHERE `Region Mine`='TN';
UPDATE `mine location` SET `Region Mine`='Texas' WHERE `Region Mine`='TX';
UPDATE `mine location` SET `Region Mine`='Utah' WHERE `Region Mine`='UT';
UPDATE `mine location` SET `Region Mine`='Vermont' WHERE `Region Mine`='VT';
UPDATE `mine location` SET `Region Mine`='Virginia' WHERE `Region Mine`='VA';
UPDATE `mine location` SET `Region Mine`='Washington' WHERE `Region Mine`='WA';
UPDATE `mine location` SET `Region Mine`='West Virginia' WHERE `Region Mine`='WV';
UPDATE `mine location` SET `Region Mine`='Wisconsin' WHERE `Region Mine`='WI';
UPDATE `mine location` SET `Region Mine`='Wyoming' WHERE `Region Mine`='WY';
UPDATE `mine location` SET `Region Mine`='American Samoa' WHERE `Region Mine`='AS';
UPDATE `mine location` SET `Region Mine`='Guam' WHERE `Region Mine`='GU';
UPDATE `mine location` SET `Region Mine`='Marshall Islands' WHERE `Region Mine`='MH';
UPDATE `mine location` SET `Region Mine`='Micronesia' WHERE `Region Mine`='FM';
UPDATE `mine location` SET `Region Mine`='Northern Marianas' WHERE `Region Mine`='MP';
UPDATE `mine location` SET `Region Mine`='Palau' WHERE `Region Mine`='PW';
UPDATE `mine location` SET `Region Mine`='Puerto Rico' WHERE `Region Mine`='PR';
UPDATE `mine location` SET `Region Mine`='Virgin Islands' WHERE `Region Mine`='VI';
UPDATE `mine location` SET `Region Mine`='British Columbia' WHERE `Region Mine`='BC';

UPDATE `mine location` SET `Country Mine`='United States' WHERE `Country Mine`='USA';

UPDATE `mine site` SET `Region Mine`='Alabama' WHERE `Region Mine`='AL';
UPDATE `mine site` SET `Region Mine`='Alaska' WHERE `Region Mine`='AK';
UPDATE `mine site` SET `Region Mine`='Arizona' WHERE `Region Mine`='AZ';
UPDATE `mine site` SET `Region Mine`='Arkansas' WHERE `Region Mine`='AR';
UPDATE `mine site` SET `Region Mine`='California' WHERE `Region Mine`='CA';
UPDATE `mine site` SET `Region Mine`='Colorado' WHERE `Region Mine`='CO';
UPDATE `mine site` SET `Region Mine`='Connecticut' WHERE `Region Mine`='CT';
UPDATE `mine site` SET `Region Mine`='Delaware' WHERE `Region Mine`='DE';
UPDATE `mine site` SET `Region Mine`='District of Columbia' WHERE `Region Mine`='DC';
UPDATE `mine site` SET `Region Mine`='Florida' WHERE `Region Mine`='FL';
UPDATE `mine site` SET `Region Mine`='Georgia' WHERE `Region Mine`='GA';
UPDATE `mine site` SET `Region Mine`='Hawaii' WHERE `Region Mine`='HI';
UPDATE `mine site` SET `Region Mine`='Idaho' WHERE `Region Mine`='ID';
UPDATE `mine site` SET `Region Mine`='Illinois' WHERE `Region Mine`='IL';
UPDATE `mine site` SET `Region Mine`='Indiana' WHERE `Region Mine`='IN';
UPDATE `mine site` SET `Region Mine`='Iowa' WHERE `Region Mine`='IA';
UPDATE `mine site` SET `Region Mine`='Kansas' WHERE `Region Mine`='KS';
UPDATE `mine site` SET `Region Mine`='Kentucky' WHERE `Region Mine`='KY';
UPDATE `mine site` SET `Region Mine`='Louisiana' WHERE `Region Mine`='LA';
UPDATE `mine site` SET `Region Mine`='Maine' WHERE `Region Mine`='ME';
UPDATE `mine site` SET `Region Mine`='Maryland' WHERE `Region Mine`='MD';
UPDATE `mine site` SET `Region Mine`='Massachusetts' WHERE `Region Mine`='MA';
UPDATE `mine site` SET `Region Mine`='Michigan' WHERE `Region Mine`='MI';
UPDATE `mine site` SET `Region Mine`='Minnesota' WHERE `Region Mine`='MN';
UPDATE `mine site` SET `Region Mine`='Mississippi' WHERE `Region Mine`='MS';
UPDATE `mine site` SET `Region Mine`='Missouri' WHERE `Region Mine`='MO';
UPDATE `mine site` SET `Region Mine`='Montana' WHERE `Region Mine`='MT';
UPDATE `mine site` SET `Region Mine`='Nebraska' WHERE `Region Mine`='NE';
UPDATE `mine site` SET `Region Mine`='Nevada' WHERE `Region Mine`='NV';
UPDATE `mine site` SET `Region Mine`='New Hampshire' WHERE `Region Mine`='NH';
UPDATE `mine site` SET `Region Mine`='New Jersey' WHERE `Region Mine`='NJ';
UPDATE `mine site` SET `Region Mine`='New Mexico' WHERE `Region Mine`='NM';
UPDATE `mine site` SET `Region Mine`='New York' WHERE `Region Mine`='NY';
UPDATE `mine site` SET `Region Mine`='North Carolina' WHERE `Region Mine`='NC';
UPDATE `mine site` SET `Region Mine`='North Dakota' WHERE `Region Mine`='ND';
UPDATE `mine site` SET `Region Mine`='Ohio' WHERE `Region Mine`='OH';
UPDATE `mine site` SET `Region Mine`='Oklahoma' WHERE `Region Mine`='OK';
UPDATE `mine site` SET `Region Mine`='Oregon' WHERE `Region Mine`='OR';
UPDATE `mine site` SET `Region Mine`='Pennsylvania' WHERE `Region Mine`='PA';
UPDATE `mine site` SET `Region Mine`='Rhode Island' WHERE `Region Mine`='RI';
UPDATE `mine site` SET `Region Mine`='South Carolina' WHERE `Region Mine`='SC';
UPDATE `mine site` SET `Region Mine`='South Dakota' WHERE `Region Mine`='SD';
UPDATE `mine site` SET `Region Mine`='Tennessee' WHERE `Region Mine`='TN';
UPDATE `mine site` SET `Region Mine`='Texas' WHERE `Region Mine`='TX';
UPDATE `mine site` SET `Region Mine`='Utah' WHERE `Region Mine`='UT';
UPDATE `mine site` SET `Region Mine`='Vermont' WHERE `Region Mine`='VT';
UPDATE `mine site` SET `Region Mine`='Virginia' WHERE `Region Mine`='VA';
UPDATE `mine site` SET `Region Mine`='Washington' WHERE `Region Mine`='WA';
UPDATE `mine site` SET `Region Mine`='West Virginia' WHERE `Region Mine`='WV';
UPDATE `mine site` SET `Region Mine`='Wisconsin' WHERE `Region Mine`='WI';
UPDATE `mine site` SET `Region Mine`='Wyoming' WHERE `Region Mine`='WY';
UPDATE `mine site` SET `Region Mine`='American Samoa' WHERE `Region Mine`='AS';
UPDATE `mine site` SET `Region Mine`='Guam' WHERE `Region Mine`='GU';
UPDATE `mine site` SET `Region Mine`='Marshall Islands' WHERE `Region Mine`='MH';
UPDATE `mine site` SET `Region Mine`='Micronesia' WHERE `Region Mine`='FM';
UPDATE `mine site` SET `Region Mine`='Northern Marianas' WHERE `Region Mine`='MP';
UPDATE `mine site` SET `Region Mine`='Palau' WHERE `Region Mine`='PW';
UPDATE `mine site` SET `Region Mine`='Puerto Rico' WHERE `Region Mine`='PR';
UPDATE `mine site` SET `Region Mine`='Virgin Islands' WHERE `Region Mine`='VI';
UPDATE `mine site` SET `Region Mine`='British Columbia' WHERE `Region Mine`='BC';
