ALTER TABLE `mine coal site production` CHANGE `MINE_ID` `ID Mine` TEXT;
ALTER TABLE `mine coal site production` CHANGE `SUBUNIT` `Subunit Mine` TEXT;
ALTER TABLE `mine coal site production` CHANGE `CAL_YR` `Year Coal Production Mine` TEXT;
ALTER TABLE `mine coal site production` CHANGE `AVG_EMPLOYEE_CNT` `Employees Mine` TEXT;
ALTER TABLE `mine coal site production` CHANGE `HOURS_WORKED` `Quarterly Employee Work Mine, Hours` TEXT;
ALTER TABLE `mine coal site production` CHANGE `COAL_PRODUCTION` `Quarterly Coal Produtcion Mine, Tons` TEXT;
ALTER TABLE `mine injury illness` CHANGE `Mine ID` `ID Mine` TEXT;
ALTER TABLE `mine injury illness` CHANGE `Controller ID @ Violations` `ID Controller Mine` TEXT;
ALTER TABLE `mine injury illness` CHANGE `Contractor ID` `ID Contractor Mine` TEXT;
ALTER TABLE `mine injury illness` CHANGE `Violator Type` `Type Violator Mine` TEXT;
ALTER TABLE `mine injury illness` CHANGE `Violation No.` `ID Violation` TEXT;
ALTER TABLE `mine injury illness` CHANGE `Violation Date Issued` `Date Violation Mine` TEXT;
ALTER TABLE `mine injury illness` CHANGE `Condition or Practice Text` `Description Violation Mine` TEXT;
ALTER TABLE `mine location` CHANGE `MINE_ID` `ID Mine` TEXT;
ALTER TABLE `mine location` CHANGE `CONTACT_TITLE` `Title Contact Mine` TEXT;
ALTER TABLE `mine location` CHANGE `NEAREST_TOWN` `City Nearby Mine` TEXT;
ALTER TABLE `mine location` CHANGE `BUSINESS_NAME` `Name Alternate Mine` TEXT;
ALTER TABLE `mine location` CHANGE `STREET` `Address Mine` TEXT;
ALTER TABLE `mine location` CHANGE `PO_BOX` `Postal Mine` TEXT;
ALTER TABLE `mine location` CHANGE `CITY` `City Mine` TEXT;
ALTER TABLE `mine location` CHANGE `STATE` `Region Mine` TEXT;
ALTER TABLE `mine location` CHANGE `COUNTRY` `Country Mine` TEXT;
ALTER TABLE `mine location` CHANGE `MINE_STATUS` `Status Contact Mine` TEXT;
ALTER TABLE `mine location` CHANGE `MINE_STATUS_DT` `Date Status Contact Mine` TEXT;
ALTER TABLE `mine operator` CHANGE `CONTROLLER_END_DT` `Date Controller End` TEXT;
ALTER TABLE `mine operator` CHANGE `CONTROLLER_ID` `ID Controller Mine Violation` TEXT;
ALTER TABLE `mine operator` CHANGE `CONTROLLER_START_DT` `Date Controller Start` TEXT;
ALTER TABLE `mine operator` CHANGE `CONTROLLER_TYPE` `Type Controller Company / Person` TEXT;
ALTER TABLE `mine operator` CHANGE `MINE_ID` `ID Mine` TEXT;
ALTER TABLE `mine operator` CHANGE `MINE_STATUS` `Status Mine Inspection` TEXT;
ALTER TABLE `mine operator` CHANGE `OPERATOR_END_DT` `Date Operator End` TEXT;
ALTER TABLE `mine operator` CHANGE `OPERATOR_START_DT` `Date Operator Start` TEXT;
ALTER TABLE `mine site` CHANGE `ASSESS_CTRL_NO` `Assessment Control Number Mine` TEXT;
ALTER TABLE `mine site` CHANGE `AVG_MINE_HEIGHT` `Average Height Coal Mine, Inches` TEXT;
ALTER TABLE `mine site` CHANGE `BOM_STATE_CD` `Region Code BOM Mine` TEXT;
ALTER TABLE `mine site` CHANGE `COAL_METAL_IND` `Type Mine Coal / Metal` TEXT;
ALTER TABLE `mine site` CHANGE `COMPANY_TYPE` `Type Organization Mine` TEXT;
ALTER TABLE `mine site` CHANGE `CONG_DIST_CD` `CONG District Mine` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_103I` `1031 Classification Mine` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_103I_DT` `Date 103I Classification Mine` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_CONTROLLER_BEGIN_DT` `Date Start Current Organization Mine` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_CONTROLLER_ID` `ID Controller Mine` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_CONTROLLER_NAME` `Name Organization Mine` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_MINE_NAME` `Name Mine Current` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_MINE_STATUS` `Status Mine` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_MINE_TYPE` `Type Mine Facility / Surface / Underground` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_OPERATOR_ID` `ID Operator Mine` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_OPERATOR_NAME` `Name Operator Mine` TEXT;
ALTER TABLE `mine site` CHANGE `CURRENT_STATUS_DT` `Date Status Mine` TEXT;
ALTER TABLE `mine site` CHANGE `DAYS_PER_WEEK` `Days per Week Mine` TEXT;
ALTER TABLE `mine site` CHANGE `DIRECTIONS_TO_MINE` `Driving Direction Mine` TEXT;
ALTER TABLE `mine site` CHANGE `DISTRICT` `District Mine` TEXT;
ALTER TABLE `mine site` CHANGE `FIPS_CNTY_NM` `FIPS Mine` TEXT;
ALTER TABLE `mine site` CHANGE `HIGHWALL_MINER_USED` `Flag, Highwall Miner Surface Coal Mine` TEXT;
ALTER TABLE `mine site` CHANGE `HOURS_PER_SHIFT` `Hours per Shift Mine` TEXT;
ALTER TABLE `mine site` CHANGE `LATITUDE` `Lat Mine` TEXT;
ALTER TABLE `mine site` CHANGE `LONGITUDE` `Long Mine` TEXT;
ALTER TABLE `mine site` CHANGE `MAINT_SHIFTS_PER_DAY` `Maintenance Shifts per Day Mine` TEXT;
ALTER TABLE `mine site` CHANGE `METHANE_LIBERATION` `Methane Mine, cft per 24 hours` TEXT;
ALTER TABLE `mine site` CHANGE `MILES_FROM_OFFICE` `Distance to Inspection Office, Miles` TEXT;
ALTER TABLE `mine site` CHANGE `MINE_ID` `ID Mine` TEXT;
ALTER TABLE `mine site` CHANGE `MINERS_REP_IND` `Flag, Miners Representative Mine` TEXT;
ALTER TABLE `mine site` CHANGE `MULTIPLE_PITS` `Flag, Multiple Pits Mine` TEXT;
ALTER TABLE `mine site` CHANGE `NO_EMPLOYEES` `Employees Mine` TEXT;
ALTER TABLE `mine site` CHANGE `NO_NONPRODUCING_PITS` `Non-Producing Coal Pits Mine` TEXT;
ALTER TABLE `mine site` CHANGE `NO_PRODUCING_PITS` `Producing Coal Pits Mine` TEXT;
ALTER TABLE `mine site` CHANGE `NO_TAILING_PONDS` `Tailing Ponds Metal Mine` TEXT;
ALTER TABLE `mine site` CHANGE `OFFICE_NAME` `Name Office Mine` TEXT;
ALTER TABLE `mine site` CHANGE `PART48_TRAINING` `Flag, Training Part 48 Mine` TEXT;
ALTER TABLE `mine site` CHANGE `PILLAR_RECOVERY_USED` `Flag, Pillar Recovery Underground Coal Mine` TEXT;
ALTER TABLE `mine site` CHANGE `PORTABLE_FIPS_ST_CD` `FIPS Portable Mine` TEXT;
ALTER TABLE `mine site` CHANGE `PORTABLE_OPERATION` `Flag, Portable Operation Mine` TEXT;
ALTER TABLE `mine site` CHANGE `PRIMARY_CANVASS` `Primary Product Mine` TEXT;
ALTER TABLE `mine site` CHANGE `PRIMARY_SIC` `SIC Mine` TEXT;
ALTER TABLE `mine site` CHANGE `PROD_SHIFTS_PER_DAY` `Production Shifts per Day Mine` TEXT;
ALTER TABLE `mine site` CHANGE `SAFETY_COMMITTEE_IND` `Flag, Safety Committee Mine` TEXT;
ALTER TABLE `mine site` CHANGE `STATE` `Region Mine` TEXT;
